### ISSUE TITLE
Multithreading over a single 400GB file is slow.

### ISSUE THREAD

**Issue by reedacartwright** [gwct/referee#3]
When processing a single input file with multiple threads, referee splits the file into multiple temporary files and then processes those files.  If a user has a large file, they will try to use multiple processes to speed the analysis; however, this causes the large file to be duplicated. Additionally, before the program splits the files, referee reads the entire file once to count the number of lines. Then reads it again to split the file. On network-backed storage, this can take a really long time, and the user won't know why referee isn't generating any output or log updates.

An alternative strategy is for referee to avoid counting lines is to measure the file size using `os.stat` and then jump a certain percentage into the file, find the next newline and split there.

Another strategy is to get rid of the temporary files and have one file-reading process and multiple data-processing processes.

**Comment by gwct** [comment]
These seem like good ideas and definite improvements over my file splitting strategy (which is admittedly sub-optimal). I will look into improving the multi-processing procedure with the following goals:

1. The input file should not be read through more than once.
2. Duplicates of the input file should not be created.

This may take some time to implement. In the meantime, I've found that splitting the input file (whether it be an ANGSD or pileup file) by scaffold and providing a file with the paths to these split files to Referee via the `-i` option can greatly improve run time, so I would recommend doing that. Hopefully that's a feasible short term solution.

**Comment by reedacartwright** [comment]
My student is working to split the file by scaffold using tabix, so I agree that is a better strategy. One solution that you could adopt in the mean time is to only support parallelizing over separate files, which would prevent users from unknowingly duplicate a 400GB input file.

**Comment by gwct** [comment]
I've gone ahead and added a max `-gl` input file size of 100GB with a message advising users to split their input file by scaffold. 

In the latest release, I've also provided shell scripts, [helper-scripts/bam_split.sh](https://github.com/gwct/referee/blob/master/helper-scripts/bam_split.sh) and [helper-scripts/tab_split.sh](https://github.com/gwct/referee/blob/master/helper-scripts/tab_split.sh), that take a large BAM (bam_split), pileup (tab_split), or ANGSD (tab_split) file and split them by scaffold using samtools or tabix. **Again, this splitting essentially duplicates the input file**, but that may be preferable to re-mapping by scaffold or re-running pileup or ANGSD by scaffold in some cases. bam_split.sh also has the option to run either mpileup or ANGSD on the split BAM files to produce input ready for Referee, so this should hopefully be helpful to others in similar situations. These scripts support multiprocessing via [GNU parallel](https://www.gnu.org/software/parallel/).

I've marked this issue as an enhancement to indicate I'll be working on improving the multiprocessing for very large files.

**Comment by gwct** [comment]
So, believe it or not I finally got some time to work on this!
I've re-vamped a lot of the code to improve logging and to change the strategy for using multiple cores. I now read through the file once line-by-line and process chunks of lines at a time (default 100,000 lines per processor). This prevents undesired duplications of the (large) input file and obviates the need for multiple read-throughs. 

With 8 cores this runs on a 20X exome (7GB input pileup) in about 40 minutes. With 16 cores it runs on a 50X whole genome (300GB pileup) in about 3 days. I can't directly compare the run-times to those in the paper because I've lost direct access to that data at my old institution, but the 300GB pileup is by far the largest file I've gotten this to complete on. Of course, I'd still like to improve on that 3 day run time!

I removed the option `-i` that allowed for multiple input files (like pileups split by scaffold) because the same can be accomplished by running Referee in multiple instances. However, I can re-add this option back in if desired.

I'd be happy to have any feedback!
