### ISSUE TITLE
Recommendation for the pileup file

### ISSUE THREAD

**Issue by ghost** [gwct/referee#5]
Hello,

I was just wondering if there were any recommendations regarding the options to use for generating the pileup file with samtools mpileup? 

EDIT: had missed the walkthrough

**Comment by gwct** [comment]
Glad you found it and it's helpful! For anyone else browsing here is the link for the recommended steps:

https://gwct.github.io/referee/walkthrough.html

With the pileup the goal is to get as much data as possible for each site, meaning we set the max depth to a ridiculously high number (`-d 999999999`) and the minimum base quality to 0 (`-Q 0`). I also disable the BAQ (`-B`) score calculation because I'm not sure how that would affect Referee's scores, though it may be ok to leave this on. Also optional is to include mapping quality (`-s`), which Referee can use in its quality score calculations.
