### ISSUE TITLE
Unable to reproduce Referee calculations from raw data

### ISSUE THREAD

**Issue by gamabunta313** [gwct/referee#7]
At the moment I am working on amplicon data from an aploid genome (same length, already aligned with a multiple alignment). Since I cannot generate a .bam file I cannot use Referee to calculate GL  and I've to call mutations from aligned fastq through base count generation and evaluation of frequency of SNVs. To validate a mutation I would like to calculate genotype likelihood, but I cannot do it efficiently since my background in statistics is not good enough.
I would like to use the formulae cited ot Referee page, but I am confused regarding the equation 3.

P(br/Ai)={(eb*em)/3 if b!=Ai || 1 - (eb*em) if b=Ai

If I am not wrong, Ai should be EACH allele for the specific read b is the position tested. Said that I would like to use the formula 4b to calculate the Log likelihood for each nucleotide. However I cannot perform the right calculation. Since I haven't the mapping qualities I assume an em=0..0001 (uniquely mapped, I used blast to map them). Assuming that in a specific position the Reference base is A and we observed 1000 A with an em=0.0001 and we see 100 G with an em=0.01, how could I calculate lilekihood to test whether the G is a virtually true mutation?
I thank you in advance for your willingness

**Comment by gwct** [comment]
Hi,
I think I understand but let me just recap to be sure. You have FASTQ files that contain base quality scores and these reads have been aligned somehow to a reference, however they are not in BAM format. From these aligned sequences you want to calculate genotype likelihoods. Is that correct?

You are right that the calculations need to be done for each allele in each genotype. Equation 1A on the [calculations page](https://gwct.github.io/referee/calcs.html) shows how this is done for both alleles (`A1` and `A2`) for a given genotype, and equation 1A is calculated for each of the 10 genotypes. Does that make sense? You may also want to check out the [original GATK paper](https://doi.org/10.1101/gr.107524.110), in which these calculations were first implemented (without mapping quality).

Regarding mapping quality, if you do not have it available you can simply leave it out of equation 3, as is done in the paper linked to above. We added it in because of the specifics of Referee requiring the mapping step, but for traditional genotype calling it is not considered.

I will also point out that there are several software packages available that can do genotype calling and may obviate the need for you to do the calculations manually, though they too may require BAM files. Some of these include [ANGSD](http://popgen.dk/angsd/index.php/ANGSD) and [bcftools](https://samtools.github.io/bcftools/bcftools.html#call).

Hope this helps! Let me know if you have any more questions.

**Comment by gamabunta313** [comment]
Everything is correct. 
Just to be sure of doing the right calculation. If I have 5 A with e=0.0001 and 2 T with e=0.0001 (we don't consider G and C for simplicity), to calculate Plog(R|g={A}) for haploid data =log(1-0.0001)+log(1-0.0001)+log(1-0.0001)+log(1-0.0001)+log(1-0.0001)+log(0.001/3)+log(0.001/3). Is it correct?
At the moment I am using the simplified formula of GATK paper and everything seems working properly. However, what I am trying to do is using the likelihood calculations to discriminate between true mutations and "hopefully" errors.
What I observed is that this formula is able to call an heterozygus if the mutation is 5-10%, however, I am interested to evaluate low frequency/good quality mutations that I know to be true (i.e. 1-2%). With this formulae, in the situation of 99% Ref 1% ALT the most likely genotype is "REF", correct if I interpreted well the formula, since the ALT nucleotides are "too few" to impact on likelihood calculation .Interestingly, if comparing 2 situations 1) 99% REF 1% ALT (TRUE mutation, all good quality) and 2) 99% REF 1% ALT (FALSE mutation, lower quality) I observed that the difference between likelihood of REF and ALT is far more high in situation 2 respect to situation 1. How can I exploit this observation? , Moreover, is that possible to "modify" formulae in order to be "more sensible" to low freq. mutations? I thank you in advance for your willingness

**Comment by gwct** [comment]
Your example calculation looks correct.

I think I need some more clarifications on your exact data:
1) First off, I just want to ensure that the species you're looking at are haploid, given that you are using the haploid version of the calculations. Your original message says "aploid," which I'm assuming is a typo of haploid? But I just want to confirm! 
2) Are you mapping the reads that made the reference back to the reference? Or are you mapping different samples to a reference? Are you mapping just one sample or multiple samples at a time?

The use case for Referee is to map the reads from which you made your reference back to the reference. In this case there is no consideration of mutation since these are the same reads -- only errors or heterozygous sites need to be accounted for. Referee certainly has potential to call mutations from new samples mapped to a reference, though I haven't tested that. For haploid data, you should be able to just take the most likely haploid genotype at each position and compare to the reference to determine if you have a mutation. There should be no need to consider whether a site is heterozygous. And this doesn't tell you if you have an error in your reference, which is Referee's original purpose -- to do that you would need to map the reads from the reference back to the reference.

Regarding your 2 scenarios:
1) 99% REF 1% ALT (TRUE mutation, all good quality): I'm not sure how this would ever happen unless you're mapping multiple samples at once. If you have a true mutation in a single sample I would expect a majority of reads to be ALT.
2) 99% REF 1% ALT (FALSE mutation, lower quality): This seems more in line with what I would expect for a sequencing error in a single read of a single sample. Given that these are low quality calls I would expect the difference between ALT and REF to be high. 

Otherwise, I guess I just need a little more info about what's going on with your data to help out!

**Comment by gamabunta313** [comment]
Since I have many doubts, I wrote you on your personal email.
